### PR TITLE
Makefiles, Collision checking, Compiled input, and Restructuring

### PR DESCRIPTION
**Pull request by brunobeltran**
A big PR. Implemented naive (n^2) and KD-tree (n log(n))-based collision checking in the BD simulations.

A Makefile now automagically generates dependencies by parsing the code using a python script, fort_depends.py. 

The code directory was renamed to src, because that just seems nicer. All references were fixed.

Finally, input now comes from a fortran module, sim_params.f90 instead of from an input file. This will be augmented by a wrapper that doesn't have to parse fortran to loop over different parameters in the future, and parallel running will then be trivial if we add a command-line flag that specifies the output directory for the simulations. During bugchecking of this new input style, wlcsim.f90 and getpara.f90 were updated to a more "modern" style.

Since the parameter input method has changed, this will probably break some people's workflows, so I'll leave the PR open for now, at least until I have a good parallel running script written.

### CODE REVIEW

**Comment by LuisNievesRosado** [comment]
Feel free to merge this. I'm going to implement the hydrodynamics this week, so I want to follow the new conventions in the code.

**Comment by brunobeltran** [comment]
Well the code as-is hasn't really decided on new conventions yet. For example, it still loads in input from a fixed file instead of reading it from the command line or taking a parameter. 

If you work on this branch I guarantee it will get merged within the next couple of days, but for now I need to get my own simulations running.

(Just fork my repo and work on the collision_checking branch)

`git remote add bruno https://github.com/brunobeltran/BasicWLC.git` then `git fetch bruno` should work.

**Comment by brunobeltran** [comment]
In fact, after looking through the code one more time, I changed my mind. Fortran is such a weak language in terms of introspection that the changes to the input style that I made are actually counter productive to most people, and maybe only I would want the code as it is here.

Maybe better to be able to specify an input directory and just read in the input file like we had before. Just use the master branch to work off of for now. We can worry about merging the changes later.

**Comment by brunobeltran** [comment]
Rebased onto #8, will make new pull request when new input style is ready.

**Pull request closed without merging**
